name: AstrowayCustomer
description: The Astrology app

publish_to: "none"
version: 1.0.1
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  in_app_review: ^2.0.11
  skeletonizer: ^2.0.1
  animated_text_kit: ^4.2.2
  audioplayers: ^6.0.0
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^6.0.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.6
  custom_clippers: ^2.0.0
  date_format: 2.0.7
  device_info_plus: ^11.0.0
  dotted_border: ^2.1.0
  draggable_widget: ^2.0.0
  easy_localization: ^3.0.5
  file_picker: ^10.2.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^2.0.4+2
  flutter_countdown_timer: ^4.1.0
  flutter_expandable_fab: ^2.3.0
  flutter_google_places_sdk: ^0.3.7
  flutter_holo_date_picker: ^1.1.0
  flutter_html: ^3.0.0-alpha.5
  flutter_image_slideshow: ^0.1.6
  flutter_inappwebview: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.2.1+2
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.0.10+1
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  lecle_yoyo_player: ^0.0.8
  onesignal_flutter: ^5.3.0
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path_provider: ^2.1.4
  pdf: ^3.11.0
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.1
  

  persistent_bottom_nav_bar_v2: ^5.3.1
  photo_view: ^0.14.0
  pin_input_text_field: ^4.5.1
  responsive_sizer: ^3.3.0+1
  scroll_screenshot: ^0.0.1
  share_plus: ^12.0.1
  shared_preferences: ^2.3.1
  smooth_page_indicator: ^1.2.1
  store_redirect: ^2.0.1
  story_view: ^0.16.5
  swipe_to: ^1.0.6
  syncfusion_flutter_gauges: ^31.1.19
  syncfusion_flutter_pdfviewer: ^31.1.19
  translator: ^1.0.3+1
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  video_player: ^2.9.1
  youtube_player_flutter: ^9.0.0
  toastification: ^3.0.2
  # google_sign_in: ^7.2.0
  google_sign_in: ^6.2.1
  flutter_foreground_task: ^9.1.0
  firebase_auth: ^6.1.3
  synchronized: ^3.3.1
  lottie: ^3.3.1
  sms_autofill: ^2.3.0

  # audio video calling libs

  agora_rtc_engine: ^6.5.2
  agora_rtm: ^2.2.5
  hmssdk_flutter: ^1.11.0
  zego_uikit_prebuilt_call: ^4.21.1
  zego_uikit_signaling_plugin: ^2.8.19
  zego_uikit_prebuilt_live_streaming: ^3.15.2
  wakelock_plus: ^1.3.3
  zego_express_engine: ^3.22.1
  screenshot: ^3.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/ringtone.mp3
    - lib/utils/noti_service.json
    - assets/images/languages/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf



